### ISSUE TITLE
Broken version 0.0.4

### ISSUE THREAD

**Issue by antoshalee** [gzigzigzeo/sidekiq-grouping#4]
Got this error on start after updating to 0.0.4

undefined method `supervise_as' for Sidekiq::Batching::Actor:Class
/Users/antoshalee/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-batching-0.0.4/lib/sidekiq/batching/supervisor.rb:9:in `run!'

**Comment by gzigzigzeo** [comment]
Try 0.0.5, please
